# Camera calibration and processing parameters

# Camera intrinsic matrix (fx, fy, cx, cy)
camera_matrix:
  - [1361.66, 0.0, 954.35]
  - [0.0, 1353.53, 539.49]
  - [0.0, 0.0, 1.0]

# Camera distortion coefficients (k1, k2, p1, p2, k3)
distortion_coeffs: [0.1557, -0.356, 0.0025, 0.0014, 0.076]

# Parameters for ArUco marker detection
aruco:
  marker_size: 0.05  # in meters
  dictionary: "DICT_4X4_250"

# Parameters for color-based segmentation (HSV)
segmentation:
  blue_hsv_lower: [90, 50, 50]
  blue_hsv_upper: [130, 255, 255]

# Parameters for SolvePnP corner detection
solvepnp:
  # 3D model points for a cube (unit size)
  object_points:
    - [0.0, 0.0, 0.0]
    - [1.0, 0.0, 0.0]
    - [1.0, 1.0, 0.0]
    - [0.0, 1.0, 0.0]
    - [0.0, 0.0, -1.0]
    - [1.0, 0.0, -1.0]
    - [1.0, 1.0, -1.0]
    - [0.0, 1.0, -1.0]
  object_size: 0.1  # Real-world size in meters (scales object_points)